#!/bin/bash

[ "$(ls -A /var/lib/mysql)" ] && echo "Running with existing database in /var/lib/mysql" || ( echo 'Populate initial db'; tar xpzvf /default_mysql.tar.gz -C /var/lib )

service mysqld start
